//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 06:45:55 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2")
package un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2;
