//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 06:45:55 PM CET 
//


package oasis.names.specification.ubl.schema.xsd.unqualifieddatatypes_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3.ns.corevocabulary.basiccomponents.AddressAddressAreaType;
import org.w3.ns.corevocabulary.basiccomponents.AddressAdminUnitLocationOneType;
import org.w3.ns.corevocabulary.basiccomponents.AddressAdminUnitLocationTwoType;
import org.w3.ns.corevocabulary.basiccomponents.AddressFullAddressType;
import org.w3.ns.corevocabulary.basiccomponents.AddressLocatorDesignatorType;
import org.w3.ns.corevocabulary.basiccomponents.AddressLocatorNameType;
import org.w3.ns.corevocabulary.basiccomponents.AddressPostCodeType;
import org.w3.ns.corevocabulary.basiccomponents.AddressPostNameType;
import org.w3.ns.corevocabulary.basiccomponents.AddressPostOfficeBoxType;
import org.w3.ns.corevocabulary.basiccomponents.AddressThoroughfareType;
import org.w3.ns.corevocabulary.basiccomponents.GeometryCoordinatesType;
import org.w3.ns.corevocabulary.basiccomponents.InputDescriptionType;
import org.w3.ns.corevocabulary.basiccomponents.InputNameType;
import org.w3.ns.corevocabulary.basiccomponents.LocationGeographicNameType;
import org.w3.ns.corevocabulary.basiccomponents.OutputDescriptionType;
import org.w3.ns.corevocabulary.basiccomponents.OutputNameType;
import org.w3.ns.corevocabulary.basiccomponents.PublicServiceDescriptionType;
import org.w3.ns.corevocabulary.basiccomponents.PublicServiceNameType;


/**
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UBLUDT0000019&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string (i.e. a finite set of characters), generally in the form of words of a language.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:RepresentationTermName xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Text&lt;/ccts:RepresentationTermName&gt;
 * </pre>
 * 
 *         
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:2" xmlns:ccts-cct="urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 *       
 * 
 * <p>Java class for TextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2>TextType">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextType")
@XmlSeeAlso({
    OutputDescriptionType.class,
    PublicServiceDescriptionType.class,
    InputDescriptionType.class,
    AddressLocatorNameType.class,
    PublicServiceNameType.class,
    AddressAddressAreaType.class,
    AddressPostCodeType.class,
    OutputNameType.class,
    AddressPostNameType.class,
    AddressLocatorDesignatorType.class,
    AddressAdminUnitLocationOneType.class,
    AddressPostOfficeBoxType.class,
    AddressAdminUnitLocationTwoType.class,
    GeometryCoordinatesType.class,
    AddressThoroughfareType.class,
    AddressFullAddressType.class,
    InputNameType.class,
    LocationGeographicNameType.class
})
public class TextType
    extends un.unece.uncefact.data.specification.corecomponenttypeschemamodule._2.TextType
{


}
