//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 06:45:55 PM CET 
//


package org.w3.ns.corevocabulary.basiccomponents;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3.ns.corevocabulary.basiccomponents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonGivenName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonGivenName");
    private final static QName _PersonGenderCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonGenderCode");
    private final static QName _InputTypeCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "InputTypeCode");
    private final static QName _AddressAdminUnitLocationOne_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressAdminUnitLocationOne");
    private final static QName _PublicServiceLanguageCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PublicServiceLanguageCode");
    private final static QName _AddressPostOfficeBox_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressPostOfficeBox");
    private final static QName _PersonAlternativeName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonAlternativeName");
    private final static QName _PersonBirthDate_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonBirthDate");
    private final static QName _AddressAdminUnitLocationTwo_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressAdminUnitLocationTwo");
    private final static QName _PublicServiceTypeCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PublicServiceTypeCode");
    private final static QName _LegalEntityAlternativeName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LegalEntityAlternativeName");
    private final static QName _GeometryCoordinates_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "GeometryCoordinates");
    private final static QName _AddressThoroughfare_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressThoroughfare");
    private final static QName _LocationGeographicID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LocationGeographicID");
    private final static QName _PeriodOfTimeStartDate_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PeriodOfTimeStartDate");
    private final static QName _LegalEntityCompanyActivityCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LegalEntityCompanyActivityCode");
    private final static QName _AddressFullAddress_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressFullAddress");
    private final static QName _InputName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "InputName");
    private final static QName _AddressID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressID");
    private final static QName _LocationGeographicName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LocationGeographicName");
    private final static QName _OutputTypeCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "OutputTypeCode");
    private final static QName _LegalEntityLegalID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LegalEntityLegalID");
    private final static QName _GeometryCoordinateReferenceSystemID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "GeometryCoordinateReferenceSystemID");
    private final static QName _LegalEntityCompanyStatusCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LegalEntityCompanyStatusCode");
    private final static QName _PersonFullName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonFullName");
    private final static QName _JurisdictionName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "JurisdictionName");
    private final static QName _JurisdictionID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "JurisdictionID");
    private final static QName _OutputDescription_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "OutputDescription");
    private final static QName _PersonID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonID");
    private final static QName _PublicServiceDescription_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PublicServiceDescription");
    private final static QName _PersonFamilyName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonFamilyName");
    private final static QName _InputDescription_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "InputDescription");
    private final static QName _PublicServiceName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PublicServiceName");
    private final static QName _AddressLocatorName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressLocatorName");
    private final static QName _PersonPatronymicName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonPatronymicName");
    private final static QName _AddressAddressArea_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressAddressArea");
    private final static QName _LegalEntityCompanyTypeCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LegalEntityCompanyTypeCode");
    private final static QName _RuleID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "RuleID");
    private final static QName _AddressPostCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressPostCode");
    private final static QName _OutputName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "OutputName");
    private final static QName _ChannelID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "ChannelID");
    private final static QName _LegalEntityLegalName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LegalEntityLegalName");
    private final static QName _PeriodOfTimeEndDate_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PeriodOfTimeEndDate");
    private final static QName _PersonDeathDate_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonDeathDate");
    private final static QName _AddressPostName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressPostName");
    private final static QName _PersonBirthName_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PersonBirthName");
    private final static QName _LegalEntityID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "LegalEntityID");
    private final static QName _AddressLocatorDesignator_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "AddressLocatorDesignator");
    private final static QName _GeometryTypeCode_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "GeometryTypeCode");
    private final static QName _PublicServiceHomepageID_QNAME = new QName("http://www.w3.org/ns/corevocabulary/BasicComponents", "PublicServiceHomepageID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3.ns.corevocabulary.basiccomponents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LegalEntityLegalIDType }
     * 
     */
    public LegalEntityLegalIDType createLegalEntityLegalIDType() {
        return new LegalEntityLegalIDType();
    }

    /**
     * Create an instance of {@link GeometryCoordinateReferenceSystemIDType }
     * 
     */
    public GeometryCoordinateReferenceSystemIDType createGeometryCoordinateReferenceSystemIDType() {
        return new GeometryCoordinateReferenceSystemIDType();
    }

    /**
     * Create an instance of {@link LegalEntityCompanyStatusCodeType }
     * 
     */
    public LegalEntityCompanyStatusCodeType createLegalEntityCompanyStatusCodeType() {
        return new LegalEntityCompanyStatusCodeType();
    }

    /**
     * Create an instance of {@link PersonFullNameType }
     * 
     */
    public PersonFullNameType createPersonFullNameType() {
        return new PersonFullNameType();
    }

    /**
     * Create an instance of {@link JurisdictionNameType }
     * 
     */
    public JurisdictionNameType createJurisdictionNameType() {
        return new JurisdictionNameType();
    }

    /**
     * Create an instance of {@link JurisdictionIDType }
     * 
     */
    public JurisdictionIDType createJurisdictionIDType() {
        return new JurisdictionIDType();
    }

    /**
     * Create an instance of {@link OutputDescriptionType }
     * 
     */
    public OutputDescriptionType createOutputDescriptionType() {
        return new OutputDescriptionType();
    }

    /**
     * Create an instance of {@link PersonIDType }
     * 
     */
    public PersonIDType createPersonIDType() {
        return new PersonIDType();
    }

    /**
     * Create an instance of {@link PublicServiceDescriptionType }
     * 
     */
    public PublicServiceDescriptionType createPublicServiceDescriptionType() {
        return new PublicServiceDescriptionType();
    }

    /**
     * Create an instance of {@link PersonFamilyNameType }
     * 
     */
    public PersonFamilyNameType createPersonFamilyNameType() {
        return new PersonFamilyNameType();
    }

    /**
     * Create an instance of {@link InputDescriptionType }
     * 
     */
    public InputDescriptionType createInputDescriptionType() {
        return new InputDescriptionType();
    }

    /**
     * Create an instance of {@link AddressLocatorNameType }
     * 
     */
    public AddressLocatorNameType createAddressLocatorNameType() {
        return new AddressLocatorNameType();
    }

    /**
     * Create an instance of {@link PersonPatronymicNameType }
     * 
     */
    public PersonPatronymicNameType createPersonPatronymicNameType() {
        return new PersonPatronymicNameType();
    }

    /**
     * Create an instance of {@link PublicServiceNameType }
     * 
     */
    public PublicServiceNameType createPublicServiceNameType() {
        return new PublicServiceNameType();
    }

    /**
     * Create an instance of {@link AddressAddressAreaType }
     * 
     */
    public AddressAddressAreaType createAddressAddressAreaType() {
        return new AddressAddressAreaType();
    }

    /**
     * Create an instance of {@link LegalEntityCompanyTypeCodeType }
     * 
     */
    public LegalEntityCompanyTypeCodeType createLegalEntityCompanyTypeCodeType() {
        return new LegalEntityCompanyTypeCodeType();
    }

    /**
     * Create an instance of {@link RuleIDType }
     * 
     */
    public RuleIDType createRuleIDType() {
        return new RuleIDType();
    }

    /**
     * Create an instance of {@link AddressPostCodeType }
     * 
     */
    public AddressPostCodeType createAddressPostCodeType() {
        return new AddressPostCodeType();
    }

    /**
     * Create an instance of {@link ChannelIDType }
     * 
     */
    public ChannelIDType createChannelIDType() {
        return new ChannelIDType();
    }

    /**
     * Create an instance of {@link OutputNameType }
     * 
     */
    public OutputNameType createOutputNameType() {
        return new OutputNameType();
    }

    /**
     * Create an instance of {@link LegalEntityLegalNameType }
     * 
     */
    public LegalEntityLegalNameType createLegalEntityLegalNameType() {
        return new LegalEntityLegalNameType();
    }

    /**
     * Create an instance of {@link PeriodOfTimeEndDateType }
     * 
     */
    public PeriodOfTimeEndDateType createPeriodOfTimeEndDateType() {
        return new PeriodOfTimeEndDateType();
    }

    /**
     * Create an instance of {@link AddressPostNameType }
     * 
     */
    public AddressPostNameType createAddressPostNameType() {
        return new AddressPostNameType();
    }

    /**
     * Create an instance of {@link PersonDeathDateType }
     * 
     */
    public PersonDeathDateType createPersonDeathDateType() {
        return new PersonDeathDateType();
    }

    /**
     * Create an instance of {@link PersonBirthNameType }
     * 
     */
    public PersonBirthNameType createPersonBirthNameType() {
        return new PersonBirthNameType();
    }

    /**
     * Create an instance of {@link LegalEntityIDType }
     * 
     */
    public LegalEntityIDType createLegalEntityIDType() {
        return new LegalEntityIDType();
    }

    /**
     * Create an instance of {@link AddressLocatorDesignatorType }
     * 
     */
    public AddressLocatorDesignatorType createAddressLocatorDesignatorType() {
        return new AddressLocatorDesignatorType();
    }

    /**
     * Create an instance of {@link GeometryTypeCodeType }
     * 
     */
    public GeometryTypeCodeType createGeometryTypeCodeType() {
        return new GeometryTypeCodeType();
    }

    /**
     * Create an instance of {@link PublicServiceHomepageIDType }
     * 
     */
    public PublicServiceHomepageIDType createPublicServiceHomepageIDType() {
        return new PublicServiceHomepageIDType();
    }

    /**
     * Create an instance of {@link PersonGivenNameType }
     * 
     */
    public PersonGivenNameType createPersonGivenNameType() {
        return new PersonGivenNameType();
    }

    /**
     * Create an instance of {@link PersonGenderCodeType }
     * 
     */
    public PersonGenderCodeType createPersonGenderCodeType() {
        return new PersonGenderCodeType();
    }

    /**
     * Create an instance of {@link InputTypeCodeType }
     * 
     */
    public InputTypeCodeType createInputTypeCodeType() {
        return new InputTypeCodeType();
    }

    /**
     * Create an instance of {@link AddressAdminUnitLocationOneType }
     * 
     */
    public AddressAdminUnitLocationOneType createAddressAdminUnitLocationOneType() {
        return new AddressAdminUnitLocationOneType();
    }

    /**
     * Create an instance of {@link PublicServiceLanguageCodeType }
     * 
     */
    public PublicServiceLanguageCodeType createPublicServiceLanguageCodeType() {
        return new PublicServiceLanguageCodeType();
    }

    /**
     * Create an instance of {@link AddressPostOfficeBoxType }
     * 
     */
    public AddressPostOfficeBoxType createAddressPostOfficeBoxType() {
        return new AddressPostOfficeBoxType();
    }

    /**
     * Create an instance of {@link PersonAlternativeNameType }
     * 
     */
    public PersonAlternativeNameType createPersonAlternativeNameType() {
        return new PersonAlternativeNameType();
    }

    /**
     * Create an instance of {@link PersonBirthDateType }
     * 
     */
    public PersonBirthDateType createPersonBirthDateType() {
        return new PersonBirthDateType();
    }

    /**
     * Create an instance of {@link PublicServiceTypeCodeType }
     * 
     */
    public PublicServiceTypeCodeType createPublicServiceTypeCodeType() {
        return new PublicServiceTypeCodeType();
    }

    /**
     * Create an instance of {@link AddressAdminUnitLocationTwoType }
     * 
     */
    public AddressAdminUnitLocationTwoType createAddressAdminUnitLocationTwoType() {
        return new AddressAdminUnitLocationTwoType();
    }

    /**
     * Create an instance of {@link LegalEntityAlternativeNameType }
     * 
     */
    public LegalEntityAlternativeNameType createLegalEntityAlternativeNameType() {
        return new LegalEntityAlternativeNameType();
    }

    /**
     * Create an instance of {@link GeometryCoordinatesType }
     * 
     */
    public GeometryCoordinatesType createGeometryCoordinatesType() {
        return new GeometryCoordinatesType();
    }

    /**
     * Create an instance of {@link AddressThoroughfareType }
     * 
     */
    public AddressThoroughfareType createAddressThoroughfareType() {
        return new AddressThoroughfareType();
    }

    /**
     * Create an instance of {@link LocationGeographicIDType }
     * 
     */
    public LocationGeographicIDType createLocationGeographicIDType() {
        return new LocationGeographicIDType();
    }

    /**
     * Create an instance of {@link PeriodOfTimeStartDateType }
     * 
     */
    public PeriodOfTimeStartDateType createPeriodOfTimeStartDateType() {
        return new PeriodOfTimeStartDateType();
    }

    /**
     * Create an instance of {@link LegalEntityCompanyActivityCodeType }
     * 
     */
    public LegalEntityCompanyActivityCodeType createLegalEntityCompanyActivityCodeType() {
        return new LegalEntityCompanyActivityCodeType();
    }

    /**
     * Create an instance of {@link AddressFullAddressType }
     * 
     */
    public AddressFullAddressType createAddressFullAddressType() {
        return new AddressFullAddressType();
    }

    /**
     * Create an instance of {@link InputNameType }
     * 
     */
    public InputNameType createInputNameType() {
        return new InputNameType();
    }

    /**
     * Create an instance of {@link AddressIDType }
     * 
     */
    public AddressIDType createAddressIDType() {
        return new AddressIDType();
    }

    /**
     * Create an instance of {@link LocationGeographicNameType }
     * 
     */
    public LocationGeographicNameType createLocationGeographicNameType() {
        return new LocationGeographicNameType();
    }

    /**
     * Create an instance of {@link OutputTypeCodeType }
     * 
     */
    public OutputTypeCodeType createOutputTypeCodeType() {
        return new OutputTypeCodeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonGivenNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonGivenName")
    public JAXBElement<PersonGivenNameType> createPersonGivenName(PersonGivenNameType value) {
        return new JAXBElement<PersonGivenNameType>(_PersonGivenName_QNAME, PersonGivenNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonGenderCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonGenderCode")
    public JAXBElement<PersonGenderCodeType> createPersonGenderCode(PersonGenderCodeType value) {
        return new JAXBElement<PersonGenderCodeType>(_PersonGenderCode_QNAME, PersonGenderCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "InputTypeCode")
    public JAXBElement<InputTypeCodeType> createInputTypeCode(InputTypeCodeType value) {
        return new JAXBElement<InputTypeCodeType>(_InputTypeCode_QNAME, InputTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressAdminUnitLocationOneType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressAdminUnitLocationOne")
    public JAXBElement<AddressAdminUnitLocationOneType> createAddressAdminUnitLocationOne(AddressAdminUnitLocationOneType value) {
        return new JAXBElement<AddressAdminUnitLocationOneType>(_AddressAdminUnitLocationOne_QNAME, AddressAdminUnitLocationOneType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicServiceLanguageCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PublicServiceLanguageCode")
    public JAXBElement<PublicServiceLanguageCodeType> createPublicServiceLanguageCode(PublicServiceLanguageCodeType value) {
        return new JAXBElement<PublicServiceLanguageCodeType>(_PublicServiceLanguageCode_QNAME, PublicServiceLanguageCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressPostOfficeBoxType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressPostOfficeBox")
    public JAXBElement<AddressPostOfficeBoxType> createAddressPostOfficeBox(AddressPostOfficeBoxType value) {
        return new JAXBElement<AddressPostOfficeBoxType>(_AddressPostOfficeBox_QNAME, AddressPostOfficeBoxType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonAlternativeNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonAlternativeName")
    public JAXBElement<PersonAlternativeNameType> createPersonAlternativeName(PersonAlternativeNameType value) {
        return new JAXBElement<PersonAlternativeNameType>(_PersonAlternativeName_QNAME, PersonAlternativeNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonBirthDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonBirthDate")
    public JAXBElement<PersonBirthDateType> createPersonBirthDate(PersonBirthDateType value) {
        return new JAXBElement<PersonBirthDateType>(_PersonBirthDate_QNAME, PersonBirthDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressAdminUnitLocationTwoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressAdminUnitLocationTwo")
    public JAXBElement<AddressAdminUnitLocationTwoType> createAddressAdminUnitLocationTwo(AddressAdminUnitLocationTwoType value) {
        return new JAXBElement<AddressAdminUnitLocationTwoType>(_AddressAdminUnitLocationTwo_QNAME, AddressAdminUnitLocationTwoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicServiceTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PublicServiceTypeCode")
    public JAXBElement<PublicServiceTypeCodeType> createPublicServiceTypeCode(PublicServiceTypeCodeType value) {
        return new JAXBElement<PublicServiceTypeCodeType>(_PublicServiceTypeCode_QNAME, PublicServiceTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalEntityAlternativeNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LegalEntityAlternativeName")
    public JAXBElement<LegalEntityAlternativeNameType> createLegalEntityAlternativeName(LegalEntityAlternativeNameType value) {
        return new JAXBElement<LegalEntityAlternativeNameType>(_LegalEntityAlternativeName_QNAME, LegalEntityAlternativeNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometryCoordinatesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "GeometryCoordinates")
    public JAXBElement<GeometryCoordinatesType> createGeometryCoordinates(GeometryCoordinatesType value) {
        return new JAXBElement<GeometryCoordinatesType>(_GeometryCoordinates_QNAME, GeometryCoordinatesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressThoroughfareType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressThoroughfare")
    public JAXBElement<AddressThoroughfareType> createAddressThoroughfare(AddressThoroughfareType value) {
        return new JAXBElement<AddressThoroughfareType>(_AddressThoroughfare_QNAME, AddressThoroughfareType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationGeographicIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LocationGeographicID")
    public JAXBElement<LocationGeographicIDType> createLocationGeographicID(LocationGeographicIDType value) {
        return new JAXBElement<LocationGeographicIDType>(_LocationGeographicID_QNAME, LocationGeographicIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodOfTimeStartDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PeriodOfTimeStartDate")
    public JAXBElement<PeriodOfTimeStartDateType> createPeriodOfTimeStartDate(PeriodOfTimeStartDateType value) {
        return new JAXBElement<PeriodOfTimeStartDateType>(_PeriodOfTimeStartDate_QNAME, PeriodOfTimeStartDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalEntityCompanyActivityCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LegalEntityCompanyActivityCode")
    public JAXBElement<LegalEntityCompanyActivityCodeType> createLegalEntityCompanyActivityCode(LegalEntityCompanyActivityCodeType value) {
        return new JAXBElement<LegalEntityCompanyActivityCodeType>(_LegalEntityCompanyActivityCode_QNAME, LegalEntityCompanyActivityCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressFullAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressFullAddress")
    public JAXBElement<AddressFullAddressType> createAddressFullAddress(AddressFullAddressType value) {
        return new JAXBElement<AddressFullAddressType>(_AddressFullAddress_QNAME, AddressFullAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "InputName")
    public JAXBElement<InputNameType> createInputName(InputNameType value) {
        return new JAXBElement<InputNameType>(_InputName_QNAME, InputNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressID")
    public JAXBElement<AddressIDType> createAddressID(AddressIDType value) {
        return new JAXBElement<AddressIDType>(_AddressID_QNAME, AddressIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationGeographicNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LocationGeographicName")
    public JAXBElement<LocationGeographicNameType> createLocationGeographicName(LocationGeographicNameType value) {
        return new JAXBElement<LocationGeographicNameType>(_LocationGeographicName_QNAME, LocationGeographicNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "OutputTypeCode")
    public JAXBElement<OutputTypeCodeType> createOutputTypeCode(OutputTypeCodeType value) {
        return new JAXBElement<OutputTypeCodeType>(_OutputTypeCode_QNAME, OutputTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalEntityLegalIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LegalEntityLegalID")
    public JAXBElement<LegalEntityLegalIDType> createLegalEntityLegalID(LegalEntityLegalIDType value) {
        return new JAXBElement<LegalEntityLegalIDType>(_LegalEntityLegalID_QNAME, LegalEntityLegalIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometryCoordinateReferenceSystemIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "GeometryCoordinateReferenceSystemID")
    public JAXBElement<GeometryCoordinateReferenceSystemIDType> createGeometryCoordinateReferenceSystemID(GeometryCoordinateReferenceSystemIDType value) {
        return new JAXBElement<GeometryCoordinateReferenceSystemIDType>(_GeometryCoordinateReferenceSystemID_QNAME, GeometryCoordinateReferenceSystemIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalEntityCompanyStatusCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LegalEntityCompanyStatusCode")
    public JAXBElement<LegalEntityCompanyStatusCodeType> createLegalEntityCompanyStatusCode(LegalEntityCompanyStatusCodeType value) {
        return new JAXBElement<LegalEntityCompanyStatusCodeType>(_LegalEntityCompanyStatusCode_QNAME, LegalEntityCompanyStatusCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFullNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonFullName")
    public JAXBElement<PersonFullNameType> createPersonFullName(PersonFullNameType value) {
        return new JAXBElement<PersonFullNameType>(_PersonFullName_QNAME, PersonFullNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "JurisdictionName")
    public JAXBElement<JurisdictionNameType> createJurisdictionName(JurisdictionNameType value) {
        return new JAXBElement<JurisdictionNameType>(_JurisdictionName_QNAME, JurisdictionNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "JurisdictionID")
    public JAXBElement<JurisdictionIDType> createJurisdictionID(JurisdictionIDType value) {
        return new JAXBElement<JurisdictionIDType>(_JurisdictionID_QNAME, JurisdictionIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "OutputDescription")
    public JAXBElement<OutputDescriptionType> createOutputDescription(OutputDescriptionType value) {
        return new JAXBElement<OutputDescriptionType>(_OutputDescription_QNAME, OutputDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonID")
    public JAXBElement<PersonIDType> createPersonID(PersonIDType value) {
        return new JAXBElement<PersonIDType>(_PersonID_QNAME, PersonIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicServiceDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PublicServiceDescription")
    public JAXBElement<PublicServiceDescriptionType> createPublicServiceDescription(PublicServiceDescriptionType value) {
        return new JAXBElement<PublicServiceDescriptionType>(_PublicServiceDescription_QNAME, PublicServiceDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFamilyNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonFamilyName")
    public JAXBElement<PersonFamilyNameType> createPersonFamilyName(PersonFamilyNameType value) {
        return new JAXBElement<PersonFamilyNameType>(_PersonFamilyName_QNAME, PersonFamilyNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "InputDescription")
    public JAXBElement<InputDescriptionType> createInputDescription(InputDescriptionType value) {
        return new JAXBElement<InputDescriptionType>(_InputDescription_QNAME, InputDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicServiceNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PublicServiceName")
    public JAXBElement<PublicServiceNameType> createPublicServiceName(PublicServiceNameType value) {
        return new JAXBElement<PublicServiceNameType>(_PublicServiceName_QNAME, PublicServiceNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressLocatorNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressLocatorName")
    public JAXBElement<AddressLocatorNameType> createAddressLocatorName(AddressLocatorNameType value) {
        return new JAXBElement<AddressLocatorNameType>(_AddressLocatorName_QNAME, AddressLocatorNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonPatronymicNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonPatronymicName")
    public JAXBElement<PersonPatronymicNameType> createPersonPatronymicName(PersonPatronymicNameType value) {
        return new JAXBElement<PersonPatronymicNameType>(_PersonPatronymicName_QNAME, PersonPatronymicNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressAddressAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressAddressArea")
    public JAXBElement<AddressAddressAreaType> createAddressAddressArea(AddressAddressAreaType value) {
        return new JAXBElement<AddressAddressAreaType>(_AddressAddressArea_QNAME, AddressAddressAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalEntityCompanyTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LegalEntityCompanyTypeCode")
    public JAXBElement<LegalEntityCompanyTypeCodeType> createLegalEntityCompanyTypeCode(LegalEntityCompanyTypeCodeType value) {
        return new JAXBElement<LegalEntityCompanyTypeCodeType>(_LegalEntityCompanyTypeCode_QNAME, LegalEntityCompanyTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "RuleID")
    public JAXBElement<RuleIDType> createRuleID(RuleIDType value) {
        return new JAXBElement<RuleIDType>(_RuleID_QNAME, RuleIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressPostCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressPostCode")
    public JAXBElement<AddressPostCodeType> createAddressPostCode(AddressPostCodeType value) {
        return new JAXBElement<AddressPostCodeType>(_AddressPostCode_QNAME, AddressPostCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "OutputName")
    public JAXBElement<OutputNameType> createOutputName(OutputNameType value) {
        return new JAXBElement<OutputNameType>(_OutputName_QNAME, OutputNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "ChannelID")
    public JAXBElement<ChannelIDType> createChannelID(ChannelIDType value) {
        return new JAXBElement<ChannelIDType>(_ChannelID_QNAME, ChannelIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalEntityLegalNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LegalEntityLegalName")
    public JAXBElement<LegalEntityLegalNameType> createLegalEntityLegalName(LegalEntityLegalNameType value) {
        return new JAXBElement<LegalEntityLegalNameType>(_LegalEntityLegalName_QNAME, LegalEntityLegalNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodOfTimeEndDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PeriodOfTimeEndDate")
    public JAXBElement<PeriodOfTimeEndDateType> createPeriodOfTimeEndDate(PeriodOfTimeEndDateType value) {
        return new JAXBElement<PeriodOfTimeEndDateType>(_PeriodOfTimeEndDate_QNAME, PeriodOfTimeEndDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonDeathDateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonDeathDate")
    public JAXBElement<PersonDeathDateType> createPersonDeathDate(PersonDeathDateType value) {
        return new JAXBElement<PersonDeathDateType>(_PersonDeathDate_QNAME, PersonDeathDateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressPostNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressPostName")
    public JAXBElement<AddressPostNameType> createAddressPostName(AddressPostNameType value) {
        return new JAXBElement<AddressPostNameType>(_AddressPostName_QNAME, AddressPostNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonBirthNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PersonBirthName")
    public JAXBElement<PersonBirthNameType> createPersonBirthName(PersonBirthNameType value) {
        return new JAXBElement<PersonBirthNameType>(_PersonBirthName_QNAME, PersonBirthNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalEntityIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "LegalEntityID")
    public JAXBElement<LegalEntityIDType> createLegalEntityID(LegalEntityIDType value) {
        return new JAXBElement<LegalEntityIDType>(_LegalEntityID_QNAME, LegalEntityIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressLocatorDesignatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "AddressLocatorDesignator")
    public JAXBElement<AddressLocatorDesignatorType> createAddressLocatorDesignator(AddressLocatorDesignatorType value) {
        return new JAXBElement<AddressLocatorDesignatorType>(_AddressLocatorDesignator_QNAME, AddressLocatorDesignatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometryTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "GeometryTypeCode")
    public JAXBElement<GeometryTypeCodeType> createGeometryTypeCode(GeometryTypeCodeType value) {
        return new JAXBElement<GeometryTypeCodeType>(_GeometryTypeCode_QNAME, GeometryTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicServiceHomepageIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/BasicComponents", name = "PublicServiceHomepageID")
    public JAXBElement<PublicServiceHomepageIDType> createPublicServiceHomepageID(PublicServiceHomepageIDType value) {
        return new JAXBElement<PublicServiceHomepageIDType>(_PublicServiceHomepageID_QNAME, PublicServiceHomepageIDType.class, null, value);
    }

}
