//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.16 at 06:45:55 PM CET 
//


package org.w3.ns.corevocabulary.aggregatecomponents;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3.ns.corevocabulary.aggregatecomponents package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Output_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "Output");
    private final static QName _PublicServiceProducesOutput_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PublicServiceProducesOutput");
    private final static QName _PersonCoreAddress_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PersonCoreAddress");
    private final static QName _RelatedCorePublicService_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "RelatedCorePublicService");
    private final static QName _AgentUsesCorePublicService_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "AgentUsesCorePublicService");
    private final static QName _CoreBusiness_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "CoreBusiness");
    private final static QName _AgentPlaysRoleCorePublicService_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "AgentPlaysRoleCorePublicService");
    private final static QName _Geometry_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "Geometry");
    private final static QName _PublicServiceInput_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PublicServiceInput");
    private final static QName _PublicServiceTemporalPeriodOfTime_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PublicServiceTemporalPeriodOfTime");
    private final static QName _AgentProvidesCorePublicService_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "AgentProvidesCorePublicService");
    private final static QName _LegalEntityCoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "LegalEntityCoreLocation");
    private final static QName _PersonCountryOfBirthCoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PersonCountryOfBirthCoreLocation");
    private final static QName _CoreAddress_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "CoreAddress");
    private final static QName _FormalFramework_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "FormalFramework");
    private final static QName _LocationCoreAddress_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "LocationCoreAddress");
    private final static QName _LegalEntityCoreAddress_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "LegalEntityCoreAddress");
    private final static QName _PersonCitizenshipJurisdiction_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PersonCitizenshipJurisdiction");
    private final static QName _PersonPlaceOfBirthCoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PersonPlaceOfBirthCoreLocation");
    private final static QName _PublicServiceFollowsRule_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PublicServiceFollowsRule");
    private final static QName _CoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "CoreLocation");
    private final static QName _Input_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "Input");
    private final static QName _PublicServicePhysicallyAvailableAtCoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PublicServicePhysicallyAvailableAtCoreLocation");
    private final static QName _PublicServiceChannel_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PublicServiceChannel");
    private final static QName _CorePerson_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "CorePerson");
    private final static QName _CreatorAgent_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "CreatorAgent");
    private final static QName _CorePublicService_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "CorePublicService");
    private final static QName _Rule_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "Rule");
    private final static QName _Jurisdiction_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "Jurisdiction");
    private final static QName _PersonPlaceOfDeathCoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PersonPlaceOfDeathCoreLocation");
    private final static QName _RegisteredCoreAddress_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "RegisteredCoreAddress");
    private final static QName _PeriodOfTime_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PeriodOfTime");
    private final static QName _PersonResidencyJurisdiction_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PersonResidencyJurisdiction");
    private final static QName _LocationGeometry_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "LocationGeometry");
    private final static QName _PublicServiceSpatialCoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PublicServiceSpatialCoreLocation");
    private final static QName _PersonCountryOfDeathCoreLocation_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "PersonCountryOfDeathCoreLocation");
    private final static QName _Channel_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "Channel");
    private final static QName _ImplementsFormalFramework_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "ImplementsFormalFramework");
    private final static QName _RequiresCorePublicService_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "RequiresCorePublicService");
    private final static QName _Agent_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "Agent");
    private final static QName _RelatedFormalFramework_QNAME = new QName("http://www.w3.org/ns/corevocabulary/AggregateComponents", "RelatedFormalFramework");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3.ns.corevocabulary.aggregatecomponents
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CorePublicServiceType }
     * 
     */
    public CorePublicServiceType createCorePublicServiceType() {
        return new CorePublicServiceType();
    }

    /**
     * Create an instance of {@link CoreBusinessType }
     * 
     */
    public CoreBusinessType createCoreBusinessType() {
        return new CoreBusinessType();
    }

    /**
     * Create an instance of {@link ChannelType }
     * 
     */
    public ChannelType createChannelType() {
        return new ChannelType();
    }

    /**
     * Create an instance of {@link CoreAddressType }
     * 
     */
    public CoreAddressType createCoreAddressType() {
        return new CoreAddressType();
    }

    /**
     * Create an instance of {@link CoreLocationType }
     * 
     */
    public CoreLocationType createCoreLocationType() {
        return new CoreLocationType();
    }

    /**
     * Create an instance of {@link InputType }
     * 
     */
    public InputType createInputType() {
        return new InputType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link OutputType }
     * 
     */
    public OutputType createOutputType() {
        return new OutputType();
    }

    /**
     * Create an instance of {@link JurisdictionType }
     * 
     */
    public JurisdictionType createJurisdictionType() {
        return new JurisdictionType();
    }

    /**
     * Create an instance of {@link FormalFrameworkType }
     * 
     */
    public FormalFrameworkType createFormalFrameworkType() {
        return new FormalFrameworkType();
    }

    /**
     * Create an instance of {@link AgentType }
     * 
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link PeriodOfTimeType }
     * 
     */
    public PeriodOfTimeType createPeriodOfTimeType() {
        return new PeriodOfTimeType();
    }

    /**
     * Create an instance of {@link GeometryType }
     * 
     */
    public GeometryType createGeometryType() {
        return new GeometryType();
    }

    /**
     * Create an instance of {@link CorePersonType }
     * 
     */
    public CorePersonType createCorePersonType() {
        return new CorePersonType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "Output")
    public JAXBElement<OutputType> createOutput(OutputType value) {
        return new JAXBElement<OutputType>(_Output_QNAME, OutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OutputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PublicServiceProducesOutput")
    public JAXBElement<OutputType> createPublicServiceProducesOutput(OutputType value) {
        return new JAXBElement<OutputType>(_PublicServiceProducesOutput_QNAME, OutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PersonCoreAddress")
    public JAXBElement<CoreAddressType> createPersonCoreAddress(CoreAddressType value) {
        return new JAXBElement<CoreAddressType>(_PersonCoreAddress_QNAME, CoreAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorePublicServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "RelatedCorePublicService")
    public JAXBElement<CorePublicServiceType> createRelatedCorePublicService(CorePublicServiceType value) {
        return new JAXBElement<CorePublicServiceType>(_RelatedCorePublicService_QNAME, CorePublicServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorePublicServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "AgentUsesCorePublicService")
    public JAXBElement<CorePublicServiceType> createAgentUsesCorePublicService(CorePublicServiceType value) {
        return new JAXBElement<CorePublicServiceType>(_AgentUsesCorePublicService_QNAME, CorePublicServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreBusinessType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "CoreBusiness")
    public JAXBElement<CoreBusinessType> createCoreBusiness(CoreBusinessType value) {
        return new JAXBElement<CoreBusinessType>(_CoreBusiness_QNAME, CoreBusinessType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorePublicServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "AgentPlaysRoleCorePublicService")
    public JAXBElement<CorePublicServiceType> createAgentPlaysRoleCorePublicService(CorePublicServiceType value) {
        return new JAXBElement<CorePublicServiceType>(_AgentPlaysRoleCorePublicService_QNAME, CorePublicServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "Geometry")
    public JAXBElement<GeometryType> createGeometry(GeometryType value) {
        return new JAXBElement<GeometryType>(_Geometry_QNAME, GeometryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PublicServiceInput")
    public JAXBElement<InputType> createPublicServiceInput(InputType value) {
        return new JAXBElement<InputType>(_PublicServiceInput_QNAME, InputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodOfTimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PublicServiceTemporalPeriodOfTime")
    public JAXBElement<PeriodOfTimeType> createPublicServiceTemporalPeriodOfTime(PeriodOfTimeType value) {
        return new JAXBElement<PeriodOfTimeType>(_PublicServiceTemporalPeriodOfTime_QNAME, PeriodOfTimeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorePublicServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "AgentProvidesCorePublicService")
    public JAXBElement<CorePublicServiceType> createAgentProvidesCorePublicService(CorePublicServiceType value) {
        return new JAXBElement<CorePublicServiceType>(_AgentProvidesCorePublicService_QNAME, CorePublicServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "LegalEntityCoreLocation")
    public JAXBElement<CoreLocationType> createLegalEntityCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_LegalEntityCoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PersonCountryOfBirthCoreLocation")
    public JAXBElement<CoreLocationType> createPersonCountryOfBirthCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_PersonCountryOfBirthCoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "CoreAddress")
    public JAXBElement<CoreAddressType> createCoreAddress(CoreAddressType value) {
        return new JAXBElement<CoreAddressType>(_CoreAddress_QNAME, CoreAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormalFrameworkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "FormalFramework")
    public JAXBElement<FormalFrameworkType> createFormalFramework(FormalFrameworkType value) {
        return new JAXBElement<FormalFrameworkType>(_FormalFramework_QNAME, FormalFrameworkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "LocationCoreAddress")
    public JAXBElement<CoreAddressType> createLocationCoreAddress(CoreAddressType value) {
        return new JAXBElement<CoreAddressType>(_LocationCoreAddress_QNAME, CoreAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "LegalEntityCoreAddress")
    public JAXBElement<CoreAddressType> createLegalEntityCoreAddress(CoreAddressType value) {
        return new JAXBElement<CoreAddressType>(_LegalEntityCoreAddress_QNAME, CoreAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PersonCitizenshipJurisdiction")
    public JAXBElement<JurisdictionType> createPersonCitizenshipJurisdiction(JurisdictionType value) {
        return new JAXBElement<JurisdictionType>(_PersonCitizenshipJurisdiction_QNAME, JurisdictionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PersonPlaceOfBirthCoreLocation")
    public JAXBElement<CoreLocationType> createPersonPlaceOfBirthCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_PersonPlaceOfBirthCoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PublicServiceFollowsRule")
    public JAXBElement<RuleType> createPublicServiceFollowsRule(RuleType value) {
        return new JAXBElement<RuleType>(_PublicServiceFollowsRule_QNAME, RuleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "CoreLocation")
    public JAXBElement<CoreLocationType> createCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_CoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "Input")
    public JAXBElement<InputType> createInput(InputType value) {
        return new JAXBElement<InputType>(_Input_QNAME, InputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PublicServicePhysicallyAvailableAtCoreLocation")
    public JAXBElement<CoreLocationType> createPublicServicePhysicallyAvailableAtCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_PublicServicePhysicallyAvailableAtCoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PublicServiceChannel")
    public JAXBElement<ChannelType> createPublicServiceChannel(ChannelType value) {
        return new JAXBElement<ChannelType>(_PublicServiceChannel_QNAME, ChannelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorePersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "CorePerson")
    public JAXBElement<CorePersonType> createCorePerson(CorePersonType value) {
        return new JAXBElement<CorePersonType>(_CorePerson_QNAME, CorePersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "CreatorAgent")
    public JAXBElement<AgentType> createCreatorAgent(AgentType value) {
        return new JAXBElement<AgentType>(_CreatorAgent_QNAME, AgentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorePublicServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "CorePublicService")
    public JAXBElement<CorePublicServiceType> createCorePublicService(CorePublicServiceType value) {
        return new JAXBElement<CorePublicServiceType>(_CorePublicService_QNAME, CorePublicServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "Rule")
    public JAXBElement<RuleType> createRule(RuleType value) {
        return new JAXBElement<RuleType>(_Rule_QNAME, RuleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "Jurisdiction")
    public JAXBElement<JurisdictionType> createJurisdiction(JurisdictionType value) {
        return new JAXBElement<JurisdictionType>(_Jurisdiction_QNAME, JurisdictionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PersonPlaceOfDeathCoreLocation")
    public JAXBElement<CoreLocationType> createPersonPlaceOfDeathCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_PersonPlaceOfDeathCoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "RegisteredCoreAddress")
    public JAXBElement<CoreAddressType> createRegisteredCoreAddress(CoreAddressType value) {
        return new JAXBElement<CoreAddressType>(_RegisteredCoreAddress_QNAME, CoreAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodOfTimeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PeriodOfTime")
    public JAXBElement<PeriodOfTimeType> createPeriodOfTime(PeriodOfTimeType value) {
        return new JAXBElement<PeriodOfTimeType>(_PeriodOfTime_QNAME, PeriodOfTimeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PersonResidencyJurisdiction")
    public JAXBElement<JurisdictionType> createPersonResidencyJurisdiction(JurisdictionType value) {
        return new JAXBElement<JurisdictionType>(_PersonResidencyJurisdiction_QNAME, JurisdictionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "LocationGeometry")
    public JAXBElement<GeometryType> createLocationGeometry(GeometryType value) {
        return new JAXBElement<GeometryType>(_LocationGeometry_QNAME, GeometryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PublicServiceSpatialCoreLocation")
    public JAXBElement<CoreLocationType> createPublicServiceSpatialCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_PublicServiceSpatialCoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoreLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "PersonCountryOfDeathCoreLocation")
    public JAXBElement<CoreLocationType> createPersonCountryOfDeathCoreLocation(CoreLocationType value) {
        return new JAXBElement<CoreLocationType>(_PersonCountryOfDeathCoreLocation_QNAME, CoreLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "Channel")
    public JAXBElement<ChannelType> createChannel(ChannelType value) {
        return new JAXBElement<ChannelType>(_Channel_QNAME, ChannelType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormalFrameworkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "ImplementsFormalFramework")
    public JAXBElement<FormalFrameworkType> createImplementsFormalFramework(FormalFrameworkType value) {
        return new JAXBElement<FormalFrameworkType>(_ImplementsFormalFramework_QNAME, FormalFrameworkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorePublicServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "RequiresCorePublicService")
    public JAXBElement<CorePublicServiceType> createRequiresCorePublicService(CorePublicServiceType value) {
        return new JAXBElement<CorePublicServiceType>(_RequiresCorePublicService_QNAME, CorePublicServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "Agent")
    public JAXBElement<AgentType> createAgent(AgentType value) {
        return new JAXBElement<AgentType>(_Agent_QNAME, AgentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormalFrameworkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/ns/corevocabulary/AggregateComponents", name = "RelatedFormalFramework")
    public JAXBElement<FormalFrameworkType> createRelatedFormalFramework(FormalFrameworkType value) {
        return new JAXBElement<FormalFrameworkType>(_RelatedFormalFramework_QNAME, FormalFrameworkType.class, null, value);
    }

}
